name: Build and publish docs

on:
    push:
        branches:
            - main

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Set yarn version to latest stable
              run: |
                  corepack enable
                  yarn set version latest

            - name: Get yarn cache directory path
              id: yarn_cache_dir
              run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

            - name: Restore Cache
              uses: actions/cache@v4
              with:
                  path: |
                      ${{ steps.yarn_cache_dir.outputs.dir }}
                      **/node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              run: |
                  yarn install --immutable

            - name: Build docs
              run: yarn jsdoc

            - name: Upload docs
              uses: actions/upload-pages-artifact@v3
              with:
                  path: docs

            - name: Publish docs
              uses: actions/deploy-pages@v4
